<a href="https://colab.research.google.com/github/Shahid-TheMatrixMaker/Shahid-TheMatrixMaker/blob/main/Numpy_array_Indexing_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr[6]

6

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [12]:
arr[:5]

array([0, 1, 2, 3, 4])

In [13]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr = np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr = arr[0:6]

In [19]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_arr[:] = 99

In [21]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [23]:
arr_copy = arr.copy

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy = arr.copy()

In [28]:
arr_copy[:] = 100

In [29]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [30]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [33]:
arr_2d =np.array([[10,15,20],[25,30,35],[40,45,50]])

In [34]:
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [35]:
arr_2d[1][1]

30

In [38]:
arr_2d[2][1]

45

In [39]:
arr_2d[0][1]

15

In [40]:
arr_2d[0,1]

15

In [41]:
arr_2d[:2,1:]

array([[15, 20],
       [30, 35]])

In [42]:
arr_2d[:2]

array([[10, 15, 20],
       [25, 30, 35]])

**Conditional Selection**

In [43]:
arr = np.arange(0,11)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
bool_arr = arr > 5

In [47]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [48]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [49]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [50]:
arr[arr<3]

array([0, 1, 2])

In [51]:
arr_2d = np.arange(50).reshape(5,10)

In [52]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [54]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

**Numpy operations**

array with array

array with scalars

Universal array functions

In [56]:
import numpy as np

In [57]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [60]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [62]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [63]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [64]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [66]:
0/1

0.0

In [67]:
arr/arr

<ipython-input-67-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [68]:
1/arr

<ipython-input-68-016353831300>:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [69]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [70]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [71]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [72]:
np.mat(arr)

matrix([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [73]:
np.max(arr)

10

In [74]:
np.min(arr)

0

In [75]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

Also check numpy documentation by searching google like scipy.org..!

In [77]:
# Create an array of 10 zeros
import numpy as np
arr = np.zeros(10)

In [78]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [79]:
# Create an array of 10 ones
arr = np.ones(10)

In [80]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [83]:
# Create an array of 10 fives
arr = np.ones(10)*5

In [84]:
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [85]:
# Create an array of the integers from 10 to 50
arr = np.arange(10,51)

In [86]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [87]:
# Create an array of all the even integers from 10 t0 50
arr = np.arange(10,51,2)

In [88]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [90]:
# Create a 3*3 matrix with values ranging from 0 to 8
arr = np.arange(0,9).reshape(3,3)

In [91]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [92]:
# Create a 3*3 identity matrix
arr = np.eye(3)

In [93]:
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [104]:
# Use numpy to generate a random number between 0 and 1
arr = np.random.rand(1)

In [105]:
arr

array([0.99154161])

In [106]:
# Use numpy to generate a array of 25 random numbers sampled from a standard normal distribution
arr = np.random.randn(25)

In [107]:
arr

array([-1.50058642,  1.32057304, -0.30108341, -1.14754977,  0.58704004,
        0.11074824,  1.94577858,  0.06448279, -0.04097023,  0.86147814,
        0.89274806, -0.38421143, -0.18834427, -0.02202614,  0.8654745 ,
        0.2139891 , -0.49761426,  0.4079012 ,  2.53924959, -0.35428963,
        0.37814019, -1.03725201,  0.74572472, -0.75358163,  1.17946292])

In [109]:
# Create an array of 20 linearly spaces points between 0 and 1
arr = np.linspace(0,1,20)

In [110]:
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])